[package]
name = "cargo-lambda"
readme = "../../README.md"
rust-version.workspace = true
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
description.workspace = true

# Use cargo-edit(https://github.com/killercup/cargo-edit#installation)
# to manage dependencies.
# Running `cargo add DEPENDENCY_NAME` will
# add the latest version of a dependency to the list,
# and it will keep the alphabetic ordering for you.
[dependencies]
cargo-lambda-build.workspace = true
cargo-lambda-deploy.workspace = true
cargo-lambda-invoke.workspace = true
cargo-lambda-new.workspace = true
cargo-lambda-watch.workspace = true
clap = { workspace = true, features = ["suggestions"] }
miette = { workspace = true, features = ["fancy"] }
reqwest = { workspace = true, features = ["rustls-tls", "json"] }
sentry = { version = "0.27.0", default-features = false, features = [
    "rustls",
    "reqwest",
    "tracing",
] }
sentry-core = "0.27.0"
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
sysinfo = "0.26.3"
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tracing.workspace = true
tracing-subscriber.workspace = true
uuid.workspace = true

[build-dependencies]
build-data = "0.1"

[dev-dependencies]
cargo-test-macro = { git = "https://github.com/rust-lang/cargo" }
cargo-test-support = { git = "https://github.com/rust-lang/cargo" }
dunce = "1.0.3"
snapbox = { version = "0.4.3", features = ["cmd", "debug"] }
