[package]
name = "cargo-lambda-remote"
description = "Cargo subcommand to work with AWS Lambda"
version = "0.8.0"
edition = "2021"
license = "MIT"
readme = "README.md"
homepage = "https://github.com/cargo-lambda/cargo-lambda"
repository = "https://github.com/cargo-lambda/cargo-lambda"
keywords = ["cargo", "subcommand", "aws", "lambda"]
rust-version = "1.59.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aws-config = "0.12.0"
aws-sdk-lambda = "0.11.0"
aws-types = "0.11.0"
clap = { version = "3.1.18", features = ["derive"] }
