[package]
name = "cargo-lambda-new"
description = "Cargo subcommand to work with AWS Lambda"
version = "0.9.0"
edition = "2021"
license = "MIT"
readme = "README.md"
homepage = "https://github.com/cargo-lambda/cargo-lambda"
repository = "https://github.com/cargo-lambda/cargo-lambda"
keywords = ["cargo", "subcommand", "aws", "lambda"]
rust-version = "1.59.0"

# Use cargo-edit(https://github.com/killercup/cargo-edit#installation)
# to manage dependencies.
# Running `cargo add DEPENDENCY_NAME` will
# add the latest version of a dependency to the list,
# and it will keep the alphabetic ordering for you.
[dependencies]
cargo-lambda-interactive = { version = "0.9.0", path = "../cargo-lambda-interactive" }
cargo-lambda-metadata = { version = "0.9.0", path = "../cargo-lambda-metadata" }
clap = { version = "3.1.18", features = ["derive"] }
liquid = "0.26.0"
miette = "4.7.1"
regex = "1.5.5"
reqwest = { version = "0.11.10", default-features = false, features = ["rustls-tls"] }
strum = "0.24.0"
strum_macros = "0.24.0"
tempfile = "3.3.0"
walkdir = "2.3.2"
zip = { version = "0.6.2", features = ["bzip2", "deflate", "time"] }
