[package]
name = "cargo-lambda-build"
description = "Cargo subcommand to work with AWS Lambda"
version = "0.6.2"
edition = "2021"
license = "MIT"
readme = "README.md"
homepage = "https://github.com/cargo-lambda/cargo-lambda"
repository = "https://github.com/cargo-lambda/cargo-lambda"
keywords = ["cargo", "subcommand", "aws", "lambda"]
rust-version = "1.59.0"

# Use cargo-edit(https://github.com/killercup/cargo-edit#installation)
# to manage dependencies.
# Running `cargo add DEPENDENCY_NAME` will
# add the latest version of a dependency to the list,
# and it will keep the alphabetic ordering for you.
[dependencies]
cargo-lambda-interactive = { version = "0.6", path = "../cargo-lambda-interactive" }
cargo-lambda-metadata = { version = "0.6", path = "../cargo-lambda-metadata" }
cargo-zigbuild = "0.8.4"
clap = { version = "3.1.8", features = ["cargo", "derive"] }
home = "0.5.3"
miette = { version = "4.3.0", features = ["fancy"] }
rustc_version = "0.4.0"
strum = "0.24.0"
strum_macros = "0.24.0"
zip = { version = "0.6.2", features = ["bzip2", "deflate", "time"] }

[dev-dependencies]
tokio = { version = "1.17.0", features = ["test-util"] }
